spring:
  profiles:
    include: oauth

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: 1234

server:
  port: 8080

logging:
  level:
    org.springframework.security: TRACE
    root: debug