spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: uCoS8KzKduaXBhiQWA35
            client-secret: QO_zFeyOfy
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver
            # redirect-uri: "http://localhost:8080/login/oauth2/code/naver"

#          google:
#            client-id: {client-id}
#            client-secret: {client-secret}
#            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
#            authorization-grant-type: authorization_code
#            scope: email
#
#          kakao:
#            client-id: {client-id(Rest Api key)}
#            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
#            client-authentication-method: POST
#            authorization-grant-type: authorization_code
#            scope: profile_nickname, profile_image, account_email

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
#          kakao:
#            authorization_uri: https://kauth.kakao.com/oauth/authorize
#            token_uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user_name_attribute: id